spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stocks
    username: postgres
    password: 647099
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  application:
    name: order
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
server:
  port: 8083

rabbitmq:
  queue:
    name: mealkit_queue
  exchange:
    name: mealkit_exchange
  routing:
    key: mealkit_routing_key

